"""
Centralized Error Catalog
Stable error codes for frontend consumption.
"""

# Assist
ASSIST_PROVIDER_UNAVAILABLE = "ASSIST.PROVIDER.UNAVAILABLE"
ASSIST_TIMEOUT = "ASSIST.TIMEOUT"
ASSIST_QUOTA_EXCEEDED = "ASSIST.QUOTA_EXCEEDED"
ASSIST_RATE_LIMIT = "ASSIST.RATE_LIMIT"
ASSIST_PROVIDER_FAILED = "ASSIST.PROVIDER.FAILED"
ASSIST_MALFORMED_RESPONSE = "ASSIST.MALFORMED_RESPONSE"

# Auth
AUTH_INVALID_TOKEN = "AUTH.TOKEN.INVALID"
AUTH_MISSING_TOKEN = "AUTH.TOKEN.MISSING"
AUTH_USER_NOT_FOUND = "AUTH.USER.NOT_FOUND"

# Safety
SAFETY_BLOCKED = "SAFETY.BLOCKED"

# System
SYSTEM_INTERNAL_ERROR = "SYSTEM.INTERNAL_ERROR"
